### PR TITLE
FIX Updated to compile in Swift 4.2

### PR DESCRIPTION
**Pull request by juanctecdam**

### CODE REVIEW

**Comment by yhkaplan** [comment]
Thanks! Looks good to me, just maybe a change to the travis config file from `osx_image: xcode9` to `osx_image: xcode10` will fix the CI issues

**Comment by juanctecdam** [comment]
Added change for Travis

**Comment by yhkaplan** [comment]
Looks like the CI is fine, what do you say @nakajijapan ?

**Review by nakajijapan — APPROVED** [review]

**Comment by nakajijapan** [comment]
@schumy Thanks for fixing!

I just merged.

**Pull request merged**
