### PR TITLE
Feature/caption customization options

### PR DESCRIPTION
**Pull request by yhkaplan**
## Changes
I added the three settings below:
1. hasCaptionShadow = true
     * Turned on by default
2. public var captionFont: UIFont?
     * Turned off if not set
3. public var captionLineHeight: CGFloat?
     * Turned off if not set

### CODE REVIEW

**Comment by yhkaplan** [comment]
@nakajijapan I plan on merging this and the other PRs today, then releasing.

**Review by nakajijapan — APPROVED** [review]

**Comment by nakajijapan** [comment]
@yhkaplan I just updated this library to v0.21.0! You can check it!!!!!1

**Comment by nakajijapan** [comment]
https://github.com/nakajijapan/PhotoSlider/releases/tag/0.21.0

**Comment by yhkaplan** [comment]
THANKS!!!! Looking good 😎

**Pull request merged**
